"""baseline: existing schema

Revision ID: 13159f923c44
Revises: 
Create Date: 2026-07-10 13:50:56.255242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13159f923c44'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('platform', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('apple_original_transaction_id', sa.String(), nullable=True))
    op.add_column('subscriptions', sa.Column('google_purchase_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'subscriptions', ['apple_original_transaction_id'])
    op.create_unique_constraint(None, 'subscriptions', ['google_purchase_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_column('subscriptions', 'google_purchase_token')
    op.drop_column('subscriptions', 'apple_original_transaction_id')
    op.drop_column('subscriptions', 'platform')
    # ### end Alembic commands ###
